
test:
  stage: test
  tags: ["ssec_shared", "docker_exec"]
  image: "rockylinux/rockylinux:latest"
  script:
    - dnf -yqq install python3-jsonschema
    - jsonschema-3 -i spacecrafts.json schema.json
