stages: ["build", "test"]

build:
  stage: build 
  tags: ["ssec_shared", "docker"]
  image: "rockylinux/rockylinux:latest"
  script:
    - dnf -yqq install jq
    - ./build.sh
  artifacts:
    paths:
      - spacecraftsdb.json

test:
  stage: test
  tags: ["ssec_shared", "docker"]
  image: "rockylinux/rockylinux:latest"
  script:
    - dnf -yqq install python3-jsonschema
    - jsonschema-3 -i spacecraftsdb.json schema.json
