stages: ["build", "test"]

build:
  stage: build 
  tags: ["ssec_shared", "docker"]
  image: "rockylinux/rockylinux:latest"
  rules:
    - if: $CI_COMMIT_TAG ~= /^\d+\.\d+\.\d+/
  script:
    - dnf -yqq install git jq
    - ./build.sh
  artifacts:
    paths:
      - spacecraftsdb.json
      - spacecraftsdb.json.sha256

test:
  stage: test
  tags: ["ssec_shared", "docker"]
  image: "rockylinux/rockylinux:latest"
  script:
    - dnf -yqq install python3-jsonschema
    - jsonschema-3 -i spacecraftsdb.json schema.json
